name: CI

on:
    push:
        branches: ["main","develop"]
    pull_request:
        branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Ruff lint
        run: ruff check .
      
      - name: Ruff format check
        run: ruff format --check .

      - name: Syntax check
        run: python -m compileall .

      - name: Run test
        run: pytest -q

      - name: Import Check (no server run)
        run: python -c "import main; from fastapi import FastAPI; assert isinstance(main.app, FastAPI)"
      
      - name: Docker Build (smoke)
        run: docker build -t cloud-notes:${{ github.sha }} . # -t = tag

      - name: Docker run + health check
        run: |
          docker run -d --rm --name cloud-notes-ci -p 8000:8000 cloud-notes:${{ github.sha }}
          sleep 5
          curl -f http://localhost:8000/health
          docker stop cloud-notes-ci
        
        # -d = background 실행, --rm : 컨테이너 종료 시 삭제, --name cloud-notes-ci = 컨테이너 이름 지정, -p 포트 포워딩